import type { DeviceVariant, MockVariant } from "@/lib/constants/business-mock-types";
import { DEMO_COMPANY_BY_INDUSTRY } from "@/lib/constants/demo-companies";

export type IndustryId = "reinigung" | "umzug" | "handwerk" | "arztpraxis";

export type ModuleShowcase = {
  id: string;
  variant: MockVariant;
  title: string;
  subtitle: string;
  problem: string;
  solution: string;
  benefit: string;
  modulesActive: string[];
  extensions: string[];
  defaultDevice: DeviceVariant;
};

export const INDUSTRY_META: Record<
  IndustryId,
  { label: string; company: string; tagline: string; accent: string }
> = {
  reinigung: {
    label: "Reinigung & Hausmeister",
    company: DEMO_COMPANY_BY_INDUSTRY.reinigung,
    tagline: "Objektverwaltung · Einsatzplanung · Qualität",
    accent: "from-sky-500 to-blue-600",
  },
  umzug: {
    label: "Umzugsunternehmen",
    company: DEMO_COMPANY_BY_INDUSTRY.umzug,
    tagline: "Disposition · Angebote · Fahrzeuge",
    accent: "from-emerald-500 to-teal-600",
  },
  handwerk: {
    label: "Handwerksbetrieb",
    company: DEMO_COMPANY_BY_INDUSTRY.handwerk,
    tagline: "Baustellen · Material · Angebote",
    accent: "from-amber-500 to-orange-600",
  },
  arztpraxis: {
    label: "Arztpraxis",
    company: DEMO_COMPANY_BY_INDUSTRY.arztpraxis,
    tagline: "Termine · Patienten · Abrechnung",
    accent: "from-teal-500 to-cyan-600",
  },
};

export const INDUSTRY_SHOWCASES: Record<IndustryId, ModuleShowcase[]> = {
  reinigung: [
    {
      id: "dashboard",
      variant: "dashboard",
      title: "Dashboard einer Reinigungsfirma",
      subtitle: "Alle Objekte, Einsätze und Umsätze auf einen Blick",
      problem: "Einsatzpläne in WhatsApp, Objektlisten in Excel — kein Gesamtüberblick.",
      solution: "Live-KPIs zu Objekten, offenen Einsätzen, Mitarbeiterauslastung und Umsatz.",
      benefit: "Sie sehen sofort, welches Objekt heute dran ist und wo Kapazität frei wird.",
      modulesActive: ["Dashboard", "Objektverwaltung", "Einsatzplanung"],
      extensions: ["Qualitätsprotokoll-Fotos", "Kundenportal", "KI-Einsatzvorschläge"],
      defaultDevice: "laptop",
    },
    {
      id: "customers",
      variant: "customers",
      title: "Kundenverwaltung — Facility & Gewerbe",
      subtitle: "Verträge, Ansprechpartner und Objektlisten pro Kunde",
      problem: "Ansprechpartner und Objektadressen verstreut — Rückfragen kosten Zeit.",
      solution: "Jeder Kunde mit Objekten, Vertragslaufzeit, Kontakthistorie und Status.",
      benefit: "Schnellere Angebotserstellung und weniger Rückfragen beim Einsatz.",
      modulesActive: ["CRM", "Objekte", "Verträge"],
      extensions: ["Automatische Verlängerung", "SLA-Tracking"],
      defaultDevice: "desktop",
    },
    {
      id: "calendar",
      variant: "calendar",
      title: "Einsatzplanung & Termine",
      subtitle: "Teams, Objekte und Schichten im Kalender",
      problem: "Doppelbelegungen und kurzfristige Umplanung per Telefon.",
      solution: "Kalender mit Team, Objekt und Fahrzeug — Drag & Drop in der Vollversion.",
      benefit: "Weniger Leerfahrten und klarere Kommunikation mit dem Team.",
      modulesActive: ["Kalender", "Mitarbeiter", "Fahrzeuge"],
      extensions: ["Mobile App fürs Team", "Push bei Planänderung"],
      defaultDevice: "tablet",
    },
    {
      id: "marketing",
      variant: "marketing",
      title: "Marketing-Dashboard",
      subtitle: "Anfragen, Kampagnen und Sichtbarkeit",
      problem: "Keine Übersicht, welche Kanäle Anfragen bringen.",
      solution: "Leads aus Website, Google und Empfehlungen in einem Marketing-Überblick.",
      benefit: "Gezielter investieren — mehr qualifizierte Objektanfragen.",
      modulesActive: ["Marketing", "Analytics", "Leads"],
      extensions: ["SEO-Reporting", "Newsletter"],
      defaultDevice: "laptop",
    },
    {
      id: "ai",
      variant: "ai",
      title: "KI-Agent für Reinigung",
      subtitle: "Einsatz-Zusammenfassungen und Kundenanfragen",
      problem: "Viele wiederkehrende Fragen zu Einsatzzeiten und Leistungen.",
      solution: "KI fasst Anfragen zusammen und schlägt Einsatzzeiten vor.",
      benefit: "Büro entlastet — Fokus auf Planung statt E-Mail-Chaos.",
      modulesActive: ["KI-Assistent", "Anfragen"],
      extensions: ["Chatbot auf Website", "Sprachassistent"],
      defaultDevice: "phone",
    },
  ],
  umzug: [
    {
      id: "dashboard",
      variant: "dashboard",
      title: "Dashboard eines Umzugsunternehmens",
      subtitle: "Aufträge, Fahrzeuge und Umsatz in Echtzeit",
      problem: "Disposition, Angebote und Rechnungen in getrennten Tools.",
      solution: "Zentrale Übersicht: offene Anfragen, Touren heute, Umsatz, Fahrzeugstatus.",
      benefit: "Weniger Leerfahrten und schnellere Reaktion auf neue Anfragen.",
      modulesActive: ["Dashboard", "Disposition", "Anfragen"],
      extensions: ["Preisrechner-Integration", "GPS-Fahrzeugtracking"],
      defaultDevice: "desktop",
    },
    {
      id: "customers",
      variant: "customers",
      title: "Kundenverwaltung — Umzug & Transport",
      subtitle: "Privat- und Firmenkunden mit Auftragshistorie",
      problem: "Kundendaten in E-Mail-Threads — kein Überblick über wiederkehrende Aufträge.",
      solution: "Kundenkartei mit Umzügen, Ansprechpartner, Umsatz und offenen Angeboten.",
      benefit: "Cross-Selling (Lagerung, Montage) und schnellere Wiederbuchungen.",
      modulesActive: ["CRM", "Angebote", "Historie"],
      extensions: ["Kundenportal mit Status", "Bewertungsanfrage"],
      defaultDevice: "laptop",
    },
    {
      id: "offers",
      variant: "offers",
      title: "Angebotsverwaltung mit Preislogik",
      subtitle: "Vom Online-Rechner zum unterschriftsreifen PDF",
      problem: "Angebote manuell in Word — Fehler bei km, Etage und Zusatzleistungen.",
      solution: "Angebote aus Preisrechner-Daten, PLZ-Distanz und Leistungspaketen.",
      benefit: "Schätzung: ca. 40–50 % schnellere Angebotserstellung (individuell).",
      modulesActive: ["Angebote", "Preisrechner", "PDF"],
      extensions: ["Digitale Unterschrift", "Automatische Nachfassung"],
      defaultDevice: "laptop",
    },
    {
      id: "invoices",
      variant: "invoices",
      title: "Rechnungsbereich",
      subtitle: "Aus Auftrag zur Rechnung ohne Doppelerfassung",
      problem: "Auftragsdaten nochmal in die Buchhaltung tippen.",
      solution: "Rechnung direkt aus abgeschlossenem Auftrag — Status und Mahnwesen.",
      benefit: "Schnellerer Cashflow und weniger Fehler.",
      modulesActive: ["Rechnungen", "Mahnwesen", "Export"],
      extensions: ["DATEV-Schnittstelle", "Stripe-Zahlung"],
      defaultDevice: "laptop",
    },
    {
      id: "calendar",
      variant: "calendar",
      title: "Disposition & Fahrzeugplanung",
      subtitle: "Touren, Teams und LKW auf einen Kalender",
      problem: "Planung auf Papier — Leerfahrten und Doppelbuchungen.",
      solution: "Touren mit Fahrzeug, Team, Start/Ziel und Zeitfenster.",
      benefit: "Mehr Aufträge pro Fahrzeug — effizientere Wochenplanung.",
      modulesActive: ["Disposition", "Fahrzeuge", "Mitarbeiter"],
      extensions: ["Mobile App für Fahrer", "Routenoptimierung"],
      defaultDevice: "tablet",
    },
    {
      id: "ai",
      variant: "ai",
      title: "KI-Agent für Umzugsanfragen",
      subtitle: "Web-Anfragen qualifizieren und Angebotsentwürfe",
      problem: "Unvollständige Anfragen — viel Hin und Her per Telefon.",
      solution: "KI erkennt fehlende Angaben und erstellt Angebotsentwürfe.",
      benefit: "Schätzung: ca. 20–30 % weniger Rückfragen-Runden.",
      modulesActive: ["KI", "Anfragen", "CRM"],
      extensions: ["WhatsApp-Integration", "Voice-to-Angebot"],
      defaultDevice: "phone",
    },
  ],
  handwerk: [
    {
      id: "dashboard",
      variant: "dashboard",
      title: "Dashboard eines Handwerksbetriebs",
      subtitle: "Baustellen, offene Angebote und Material auf einen Blick",
      problem: "Chef weiß nicht auf einen Blick, welche Baustelle Priorität hat.",
      solution: "KPIs zu Baustellen, Angeboten, Material und Team-Auslastung.",
      benefit: "Bessere Tagesplanung — weniger Chaos auf der Baustelle.",
      modulesActive: ["Dashboard", "Baustellen", "Angebote"],
      extensions: ["Wetter-Widget", "Subunternehmer"],
      defaultDevice: "laptop",
    },
    {
      id: "customers",
      variant: "customers",
      title: "Kundenverwaltung — Handwerk",
      subtitle: "Bauherren, Gewerbe und Wartungsverträge",
      problem: "Kundendaten in Handy-Kontakten und Zetteln.",
      solution: "Strukturierte Kunden mit Baustellen, Angeboten und Fotodokumentation.",
      benefit: "Professioneller Auftritt und schnellere Nachfolgeaufträge.",
      modulesActive: ["CRM", "Baustellen", "Dokumente"],
      extensions: ["Wartungsintervalle", "Garantie-Tracking"],
      defaultDevice: "laptop",
    },
    {
      id: "offers",
      variant: "offers",
      title: "Angebotserstellung auf der Baustelle",
      subtitle: "Positionen, Material und Fotos im Angebot",
      problem: "Angebote abends im Büro nacharbeiten — Details vergessen.",
      solution: "Angebot mit Leistungspositionen, Material und Baustellenfotos.",
      benefit: "Schnellere Kalkulation und höhere Abschlussquote.",
      modulesActive: ["Angebote", "Material", "Fotos"],
      extensions: ["GAEB-Export", "Digitale Unterschrift"],
      defaultDevice: "tablet",
    },
    {
      id: "employees",
      variant: "employees",
      title: "Mitarbeiterverwaltung",
      subtitle: "Teams, Qualifikationen und Einsätze",
      problem: "Unklar, wer welche Qualifikation auf welcher Baustelle hat.",
      solution: "Mitarbeiterprofile mit Skills, Einsatzhistorie und Zeiterfassung.",
      benefit: "Richtiges Team auf der richtigen Baustelle — weniger Nacharbeit.",
      modulesActive: ["Personal", "Zeiterfassung", "Kalender"],
      extensions: ["Lohnexport", "Fahrzeugzuweisung"],
      defaultDevice: "laptop",
    },
    {
      id: "documents",
      variant: "documents",
      title: "Dokumentenverwaltung",
      subtitle: "Pläne, Fotos und Abnahmen pro Baustelle",
      problem: "Fotos und Pläne in WhatsApp-Gruppen — nicht auffindbar.",
      solution: "Alle Unterlagen pro Baustelle: Fotos, Pläne, Protokolle, Rechnungen.",
      benefit: "Rechtssicherheit und schnelle Klärung bei Reklamationen.",
      modulesActive: ["DMS", "Fotos", "PDF"],
      extensions: ["KI-Dokumentensuche", "Kundenfreigabe"],
      defaultDevice: "desktop",
    },
    {
      id: "analytics",
      variant: "analytics",
      title: "Analytics & Auswertungen",
      subtitle: "Umsatz, Marge und Auslastung",
      problem: "Keine Auswertung, welche Leistungen profitabel sind.",
      solution: "Diagramme zu Umsatz, Baustellen-Marge und Team-Auslastung.",
      benefit: "Bessere Preisgestaltung und strategische Entscheidungen.",
      modulesActive: ["Analytics", "Reporting", "Dashboard"],
      extensions: ["Prognosen", "Export für Steuerberater"],
      defaultDevice: "desktop",
    },
  ],
  arztpraxis: [
    {
      id: "dashboard",
      variant: "dashboard",
      title: "Dashboard einer Arztpraxis",
      subtitle: "Termine, Patienten und Abrechnung auf einen Blick",
      problem: "Terminkalender, Patientenakten und Abrechnung in getrennten Systemen.",
      solution: "Zentrale Praxis-Übersicht: Termine heute, Warteliste, offene Abrechnungen, Team.",
      benefit: "Ruhigerer Praxisalltag — weniger Medienbrüche an der Anmeldung.",
      modulesActive: ["Dashboard", "Termine", "Patienten"],
      extensions: ["Online-Terminbuchung", "Recall-System", "eAU-Export"],
      defaultDevice: "laptop",
    },
    {
      id: "customers",
      variant: "customers",
      title: "Patientenverwaltung",
      subtitle: "Stammdaten, Versicherung und Besuchshistorie",
      problem: "Patientendaten verteilt — Rückfragen bei wiederkehrenden Terminen.",
      solution: "Patientenkartei mit Versicherung, letztem Besuch, Recall und Dokumenten.",
      benefit: "Schnellere Anmeldung und professionellerer Patientenservice.",
      modulesActive: ["Patienten", "Versicherung", "Historie"],
      extensions: ["DSGVO-konforme Akte", "Familienverknüpfung"],
      defaultDevice: "desktop",
    },
    {
      id: "calendar",
      variant: "calendar",
      title: "Praxis-Kalender & Termine",
      subtitle: "Behandler, Räume und Online-Buchungen",
      problem: "Doppelbelegungen und telefonische Terminchaos in Stoßzeiten.",
      solution: "Kalender mit Behandler, Raum, Behandlungsart und Warteliste.",
      benefit: "Weniger Leerlauf und kürzere Wartezeiten in der Anmeldung.",
      modulesActive: ["Termine", "Behandler", "Räume"],
      extensions: ["SMS-Erinnerung", "Videosprechstunde"],
      defaultDevice: "tablet",
    },
    {
      id: "documents",
      variant: "documents",
      title: "Dokumente & Befunde",
      subtitle: "Befunde, Überweisungen und Patientenunterlagen",
      problem: "Papierstapel und fehlende Zuordnung zu Terminen.",
      solution: "Alle Unterlagen pro Patient und Termin — durchsuchbar und versioniert.",
      benefit: "Schnellere Nachverfolgung und weniger Suchzeit am Empfang.",
      modulesActive: ["DMS", "Befunde", "PDF"],
      extensions: ["KI-Zusammenfassung", "Sicherer Patienten-Upload"],
      defaultDevice: "laptop",
    },
    {
      id: "invoices",
      variant: "invoices",
      title: "Abrechnung & Finanzen",
      subtitle: "GOÄ/EBM, Status und Export",
      problem: "Abrechnung manuell nachbearbeiten — Fehler bei Kassen und Privat.",
      solution: "Abrechnungsübersicht mit Status, Mahnwesen und Export für Abrechnungsdienst.",
      benefit: "Schnellerer Cashflow und weniger Rückläufer.",
      modulesActive: ["Abrechnung", "Export", "Reporting"],
      extensions: ["Schnittstelle Abrechnungszentrum", "Statistik nach Behandler"],
      defaultDevice: "laptop",
    },
    {
      id: "ai",
      variant: "ai",
      title: "KI-Assistent für die Anmeldung",
      subtitle: "Terminanfragen und Recall-Vorschläge",
      problem: "Wiederkehrende Anrufe zu Terminen, Rezepten und Öffnungszeiten.",
      solution: "KI qualifiziert Anfragen und schlägt freie Termine vor.",
      benefit: "Entlastung der Anmeldung — Fokus auf Patienten vor Ort.",
      modulesActive: ["KI", "Termine", "Anfragen"],
      extensions: ["Website-Chatbot", "Telefon-Assistent"],
      defaultDevice: "phone",
    },
  ],
};

export const ALL_MODULE_TABS: { variant: MockVariant; label: string }[] = [
  { variant: "dashboard", label: "Dashboard" },
  { variant: "customers", label: "Kunden" },
  { variant: "offers", label: "Angebote" },
  { variant: "invoices", label: "Rechnungen" },
  { variant: "employees", label: "Mitarbeiter" },
  { variant: "calendar", label: "Termine" },
  { variant: "documents", label: "Dokumente" },
  { variant: "marketing", label: "Marketing" },
  { variant: "analytics", label: "Analytics" },
  { variant: "ai", label: "KI-Agent" },
];
