/**
 * UNZE Business Shop — öffentlicher Produktkatalog (SSOT Code)
 * Sync mit CORSA: 07_Vorlagen/Leistungskatalog_Vorlage.json
 * Studio verwaltet später DB-Spiegel; Code bleibt Fallback.
 */

export type ShopProductType =
  | "analyse"
  | "grund"
  | "template"
  | "pauschal"
  | "servicepaket";

export type ShopProduct = {
  id: string;
  slug: string;
  name: string;
  shortDescription: string;
  longDescription?: string;
  category: string;
  type: ShopProductType;
  priceCents: number;
  priceLabel?: string;
  priceNote?: string;
  processingTime: string;
  highlights: string[];
  /** Öffentlich buchbar — nur Analyse + Servicepakete (Regel B-S11) */
  purchasable: boolean;
  /** Studio-intern: voller Katalog für Angebote & Aufträge */
  studioCatalog?: boolean;
  /** Stripe subscription for service packages */
  billingInterval?: "month";
  /** After payment: redirect hint for analyse products */
  postPurchasePath?: string;
};

export const SHOP_TAX_RATE = 0;

export const SHOP_PRODUCTS: readonly ShopProduct[] = [
  {
    id: "analyse-quick",
    slug: "analyse-quick",
    name: "Quick Analyse",
    shortDescription: "Öffentliche Websiteanalyse mit PDF-Bericht",
    category: "Analyse",
    type: "analyse",
    priceCents: 5990,
    priceLabel: "59,90 €",
    processingTime: "1–3 Werktage",
    highlights: ["Website-Check", "SEO-Eindruck", "PDF-Bericht", "Erste Empfehlungen"],
    purchasable: true,
    postPurchasePath: "/business/analyse?tier=quick",
  },
  {
    id: "analyse-business",
    slug: "analyse-business",
    name: "Business Analyse",
    shortDescription: "Vertiefte Unternehmensanalyse nach Fragebogen",
    category: "Analyse",
    type: "analyse",
    priceCents: 24900,
    priceLabel: "ab 249 €",
    priceNote: "Gutschrift bei Projektbeauftragung",
    processingTime: "3–7 Werktage",
    highlights: ["Prozessanalyse", "Automatisierungspotenzial", "Modul-Empfehlung", "Professioneller Bericht"],
    purchasable: true,
    postPurchasePath: "/business/analyse?tier=business",
  },
  {
    id: "analyse-premium",
    slug: "analyse-premium",
    name: "Premium Analyse",
    shortDescription: "Strategieberatung mit persönlichem Gespräch",
    category: "Analyse",
    type: "analyse",
    priceCents: 49000,
    priceLabel: "ab 490 €",
    priceNote: "Gutschrift bei Umsetzung",
    processingTime: "Nach Terminvereinbarung",
    highlights: ["Persönliches Gespräch", "Roadmap", "Strategie", "Konkretes Angebot"],
    purchasable: true,
    postPurchasePath: "/business/analyse?tier=premium",
  },
  {
    id: "domain-einrichtung",
    slug: "domain-einrichtung",
    name: "Domain-Einrichtung",
    shortDescription: "Professionelle Einrichtung Ihrer Domain",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 3990,
    priceLabel: "39,90 €",
    processingTime: "1–2 Werktage",
    highlights: ["DNS-Basis", "Weiterleitung", "Dokumentation"],
    purchasable: true,
  },
  {
    id: "domain-umzug",
    slug: "domain-umzug",
    name: "Domain-Umzug",
    shortDescription: "Sicherer Umzug zu Ihrem Wunsch-Anbieter",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 5990,
    priceLabel: "59,90 €",
    processingTime: "2–5 Werktage",
    highlights: ["Auth-Code", "Minimaler Ausfall", "Checkliste"],
    purchasable: true,
  },
  {
    id: "dns-konfiguration",
    slug: "dns-konfiguration",
    name: "DNS-Konfiguration",
    shortDescription: "Einträge, Subdomains, E-Mail-Records",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 2990,
    priceLabel: "29,90 €",
    processingTime: "1–2 Werktage",
    highlights: ["A/AAAA/CNAME", "MX/TXT", "Test & Protokoll"],
    purchasable: true,
  },
  {
    id: "hosting-einrichtung",
    slug: "hosting-einrichtung",
    name: "Hosting-Einrichtung (Vercel)",
    shortDescription: "Deployment, Domain-Anbindung, Basis-Config",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 7990,
    priceLabel: "79,90 €",
    processingTime: "2–3 Werktage",
    highlights: ["Vercel-Projekt", "Env-Variablen", "Deploy-Pipeline"],
    purchasable: true,
  },
  {
    id: "email-einrichtung",
    slug: "email-einrichtung",
    name: "Geschäftliche E-Mail einrichten",
    shortDescription: "Postfächer und Client-Konfiguration",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 3990,
    priceLabel: "39,90 €",
    processingTime: "1–3 Werktage",
    highlights: ["MX-Records", "Postfach", "Kurze Einweisung"],
    purchasable: true,
  },
  {
    id: "google-workspace-einrichtung",
    slug: "google-workspace-einrichtung",
    name: "Google Workspace einrichten",
    shortDescription: "Workspace-Setup für Ihr Team",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 9990,
    priceLabel: "99,90 €",
    processingTime: "2–4 Werktage",
    highlights: ["Domain-Verifizierung", "Nutzer", "Grundkonfiguration"],
    purchasable: true,
  },
  {
    id: "supabase-einrichtung",
    slug: "supabase-einrichtung",
    name: "Supabase einrichten",
    shortDescription: "Datenbank, Auth, Storage — produktionsbereit",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 14900,
    priceLabel: "149 €",
    processingTime: "3–5 Werktage",
    highlights: ["Projekt-Setup", "RLS-Basis", "Region EU"],
    purchasable: true,
  },
  {
    id: "vercel-einrichtung",
    slug: "vercel-einrichtung",
    name: "Vercel einrichten",
    shortDescription: "Hosting für Next.js & moderne Web-Apps",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 14900,
    priceLabel: "149 €",
    processingTime: "2–4 Werktage",
    highlights: ["Team-Zugang", "Domains", "Preview-Deploys"],
    purchasable: true,
  },
  {
    id: "datenbank-grundkonfiguration",
    slug: "datenbank-grundkonfiguration",
    name: "Datenbank-Grundkonfiguration",
    shortDescription: "Schema, Backups, Sicherheitsbasis",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 19900,
    priceLabel: "199 €",
    processingTime: "3–7 Werktage",
    highlights: ["Migrationen", "Backup-Plan", "Monitoring-Hinweise"],
    purchasable: true,
  },
  {
    id: "backup-konfiguration",
    slug: "backup-konfiguration",
    name: "Backup-Konfiguration",
    shortDescription: "Automatische Sicherungen einrichten",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 9900,
    priceLabel: "99 €",
    processingTime: "2–3 Werktage",
    highlights: ["Zeitplan", "Restore-Test", "Dokumentation"],
    purchasable: true,
  },
  {
    id: "monitoring",
    slug: "monitoring",
    name: "Monitoring einrichten",
    shortDescription: "Verfügbarkeit und Fehler-Alerts",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 4900,
    priceLabel: "49 €",
    processingTime: "1–2 Werktage",
    highlights: ["Uptime-Check", "Benachrichtigung", "Dashboard-Link"],
    purchasable: true,
  },
  {
    id: "stripe-einrichtung",
    slug: "stripe-einrichtung",
    name: "Stripe-Einrichtung",
    shortDescription: "Zahlungen und Webhooks konfigurieren",
    category: "Integration",
    type: "pauschal",
    priceCents: 14900,
    priceLabel: "149 €",
    processingTime: "3–5 Werktage",
    highlights: ["Checkout", "Webhooks", "Testmodus → Live"],
    purchasable: true,
  },
  {
    id: "api-anbindung",
    slug: "api-anbindung",
    name: "API-Anbindung",
    shortDescription: "Schnittstelle zu Drittsystem",
    category: "Integration",
    type: "pauschal",
    priceCents: 14900,
    priceLabel: "ab 149 €",
    priceNote: "Nach Scope-Gespräch",
    processingTime: "5–10 Werktage",
    highlights: ["REST/Webhook", "Auth", "Fehlerbehandlung"],
    purchasable: true,
  },
  {
    id: "whatsapp-integration",
    slug: "whatsapp-integration",
    name: "WhatsApp-Integration",
    shortDescription: "Business-Kanal anbinden",
    category: "Integration",
    type: "pauschal",
    priceCents: 19900,
    priceLabel: "ab 199 €",
    processingTime: "5–10 Werktage",
    highlights: ["API-Setup", "Templates", "Webhook"],
    purchasable: true,
  },
  {
    id: "ssl-konfiguration",
    slug: "ssl-konfiguration",
    name: "SSL-Konfiguration & Prüfung",
    shortDescription: "HTTPS, Zertifikat, Weiterleitungen",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 2990,
    priceLabel: "29,90 €",
    processingTime: "1 Werktag",
    highlights: ["HTTPS erzwingen", "Zertifikats-Check", "HSTS optional"],
    purchasable: true,
  },
  {
    id: "domain-registrierung-service",
    slug: "domain-registrierung-service",
    name: "Domain-Registrierung (Service)",
    shortDescription: "Wir registrieren Ihre Wunsch-Domain beim Provider",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 2990,
    priceLabel: "29,90 €",
    priceNote: "zzgl. Domain-Jahrespreis beim Anbieter",
    processingTime: "1–3 Werktage",
    highlights: ["Verfügbarkeitsprüfung", "Registrierung", "DNS-Start"],
    purchasable: true,
  },
  {
    id: "bundle-domain-hosting",
    slug: "bundle-domain-hosting",
    name: "Paket: Domain + Hosting-Einrichtung",
    shortDescription: "Domain und Vercel-Setup im Paket",
    category: "Infrastruktur",
    type: "pauschal",
    priceCents: 9990,
    priceLabel: "99,90 €",
    processingTime: "2–4 Werktage",
    highlights: ["Domain-Einrichtung", "Vercel-Deploy", "SSL-Basis"],
    purchasable: true,
  },
  {
    id: "seo-basis-setup",
    slug: "seo-basis-setup",
    name: "SEO-Basis Setup",
    shortDescription: "Meta, Sitemap, Search Console Anstoß",
    category: "Marketing",
    type: "pauschal",
    priceCents: 9900,
    priceLabel: "99 €",
    processingTime: "3–5 Werktage",
    highlights: ["Meta-Tags", "Sitemap", "robots.txt", "Search Console"],
    purchasable: true,
  },
  {
    id: "impressum-datenschutz-setup",
    slug: "impressum-datenschutz-setup",
    name: "Impressum & Datenschutz (technisch)",
    shortDescription: "Seiten anlegen, verlinken, Struktur — Texte durch Kunde/Anwalt",
    category: "Marketing",
    type: "pauschal",
    priceCents: 7900,
    priceLabel: "79 €",
    processingTime: "2–3 Werktage",
    highlights: ["Routes /impressum /datenschutz", "Footer-Links", "Platzhalter-Struktur"],
    purchasable: true,
  },
  {
    id: "cookie-consent-setup",
    slug: "cookie-consent-setup",
    name: "Cookie-Banner & Consent",
    shortDescription: "DSGVO-konformes Banner einbinden",
    category: "Marketing",
    type: "pauschal",
    priceCents: 4900,
    priceLabel: "49 €",
    processingTime: "1–2 Werktage",
    highlights: ["Banner", "Kategorien", "Script-Blocking Basis"],
    purchasable: true,
  },
  {
    id: "performance-optimierung",
    slug: "performance-optimierung",
    name: "Performance-Optimierung",
    shortDescription: "Ladezeit, Bilder, Core Web Vitals Basis",
    category: "Marketing",
    type: "pauschal",
    priceCents: 14900,
    priceLabel: "149 €",
    processingTime: "3–7 Werktage",
    highlights: ["Analyse", "Bilder", "Caching-Hinweise", "Kurzbericht"],
    purchasable: true,
  },
  {
    id: "template-landingpage",
    slug: "template-landingpage",
    name: "Landingpage — individuelles Design",
    shortDescription: "Stilrichtung wählen, Inhalte angeben — UNZE erstellt Ihre Seite im Designstudio",
    longDescription:
      "Kein Datei-Download. Sie orientieren sich an unseren Branchen-Vorlagen (Umzug, Reinigung, Praxis, Handwerk) und liefern Texte & Wünsche. Wir gestalten Ihre Landingpage individuell.",
    category: "Templates",
    type: "template",
    priceCents: 2900,
    priceLabel: "29 €",
    priceNote: "Designstudio-Einstieg · kein Download · Projekt ab 390 €",
    processingTime: "3–5 Werktage",
    highlights: [
      "Stilrichtung aus Branchen-Vorlagen",
      "Briefing-Formular nach Zahlung",
      "Individuelles Design im Designstudio",
      "Responsive & modern",
    ],
    purchasable: true,
  },
  {
    id: "template-business-website",
    slug: "template-business-website",
    name: "Business-Website — individuelles Design",
    shortDescription: "Mehrseitige Website nach Ihren Angaben — erstellt im UNZE Designstudio",
    category: "Templates",
    type: "template",
    priceCents: 5900,
    priceLabel: "59 €",
    priceNote: "Designstudio · mehrseitig · Projekt ab 790 €",
    processingTime: "5–8 Werktage",
    highlights: [
      "Mehrere Seiten (Start, Leistungen, Kontakt …)",
      "Corporate Look — individuell angepasst",
      "Briefing mit Inhalten & Wunsch-Look",
      "Go-Live durch UNZE",
    ],
    purchasable: true,
  },
  {
    id: "template-website-admin",
    slug: "template-website-admin",
    name: "Website + Admin — individuelles Design",
    shortDescription: "Website mit Admin-Bereich — Inhalte selbst pflegen, Design von UNZE",
    category: "Templates",
    type: "template",
    priceCents: 19900,
    priceLabel: "199 €",
    priceNote: "Briefing nach Buchung",
    processingTime: "7–10 Werktage",
    highlights: [
      "Öffentliche Website + Admin-Basis",
      "Inhalte selbst pflegen",
      "Individuelles Designstudio-Layout",
      "Einweisung inklusive",
    ],
    purchasable: true,
  },
  {
    id: "template-webapp",
    slug: "template-webapp",
    name: "Web-App — individuelles Design",
    shortDescription: "Dashboard & App-Oberfläche nach Briefing — Business-Core-Stil",
    category: "Templates",
    type: "template",
    priceCents: 24900,
    priceLabel: "249 €",
    priceNote: "App-Oberfläche · Scope im Briefing · Projekt ab 3.990 €",
    processingTime: "10–14 Werktage",
    highlights: [
      "Dashboard-Basis nach Branchen-Vorlage",
      "Auth-Vorbereitung",
      "Individuelle Anpassung im Designstudio",
      "Abstimmung vor Umsetzung",
    ],
    purchasable: true,
  },
  {
    id: "template-modul-bewertungen",
    slug: "template-modul-bewertungen",
    name: "Modul: Bewertungen",
    shortDescription: "Bewertungs-Bereich für Ihre Website — Design passend zu Ihrem Auftritt",
    category: "Templates",
    type: "template",
    priceCents: 2900,
    priceLabel: "29 €",
    processingTime: "2–4 Werktage",
    highlights: ["Bewertungs-UI", "An Ihr Design angepasst", "Integration in bestehende Seite"],
    purchasable: true,
  },
  {
    id: "template-modul-termin",
    slug: "template-modul-termin",
    name: "Modul: Termin / Anfrage",
    shortDescription: "Buchungs- oder Anfrage-Modul — passend zu Ihrer Website",
    category: "Templates",
    type: "template",
    priceCents: 2900,
    priceLabel: "29 €",
    processingTime: "2–4 Werktage",
    highlights: ["Formular-Flow", "Kalender-/Anfrage-Basis", "Designstudio-Anpassung"],
    purchasable: true,
  },
  {
    id: "einrichtung-template-standard",
    slug: "einrichtung-template-standard",
    name: "Website-Einrichtung Standard",
    shortDescription: "Deploy & Domain-Anbindung für Ihre bei UNZE erstellte Website",
    category: "Einrichtung",
    type: "pauschal",
    priceCents: 19900,
    priceLabel: "199 €",
    processingTime: "3–5 Werktage",
    highlights: ["Deploy", "Domain-Anbindung", "Basis-Inhalte live", "SSL-Basis"],
    purchasable: true,
  },
  {
    id: "einrichtung-template-pro",
    slug: "einrichtung-template-pro",
    name: "Website-Einrichtung Pro",
    shortDescription: "Go-Live plus Anpassungen und Abnahme-Call",
    category: "Einrichtung",
    type: "pauschal",
    priceCents: 49900,
    priceLabel: "499 €",
    processingTime: "5–10 Werktage",
    highlights: ["Design-Feinschliff", "Inhalte einpflegen", "Abnahme-Call", "Go-Live"],
    purchasable: true,
  },
  {
    id: "newsletter-anbindung",
    slug: "newsletter-anbindung",
    name: "Newsletter-Anbindung",
    shortDescription: "Formular + Provider (z. B. Brevo, Mailchimp)",
    category: "Integration",
    type: "pauschal",
    priceCents: 9900,
    priceLabel: "99 €",
    processingTime: "2–4 Werktage",
    highlights: ["Double-Opt-In Basis", "Formular", "Provider-Connect"],
    purchasable: true,
  },
  {
    id: "kalender-buchungssystem",
    slug: "kalender-buchungssystem",
    name: "Online-Terminbuchung einrichten",
    shortDescription: "Buchungsflow für Ihre Website",
    category: "Integration",
    type: "pauschal",
    priceCents: 19900,
    priceLabel: "199 €",
    processingTime: "5–8 Werktage",
    highlights: ["Termin-Wizard", "E-Mail-Bestätigung", "Admin-Basis"],
    purchasable: true,
  },
  {
    id: "cms-wordpress-migration",
    slug: "cms-wordpress-migration",
    name: "WordPress → Modern Stack Beratung",
    shortDescription: "Analyse & Migrationsplan",
    category: "Einrichtung",
    type: "pauschal",
    priceCents: 24900,
    priceLabel: "249 €",
    processingTime: "5–7 Werktage",
    highlights: ["Ist-Analyse", "Migrationsplan", "Aufwandsschätzung"],
    purchasable: true,
  },
  {
    id: "technische-beratung-stunde",
    slug: "technische-beratung-stunde",
    name: "Technische Beratung (1 Stunde)",
    shortDescription: "Video/Telefon — konkrete Fragen klären",
    category: "Beratung",
    type: "pauschal",
    priceCents: 8900,
    priceLabel: "89 €",
    processingTime: "Termin nach Buchung",
    highlights: ["60 Minuten", "Protokoll per E-Mail", "Keine Umsetzung inkl."],
    purchasable: true,
  },
  {
    id: "wartung-einmal-check",
    slug: "wartung-einmal-check",
    name: "Wartungs- & Sicherheits-Check",
    shortDescription: "Einmaliger Health-Check Ihrer Website",
    category: "Service",
    type: "pauschal",
    priceCents: 9900,
    priceLabel: "99 €",
    processingTime: "2–3 Werktage",
    highlights: ["Updates-Status", "SSL", "Backup-Check", "Kurzbericht"],
    purchasable: true,
  },
  {
    id: "servicepaket-basis",
    slug: "servicepaket-basis",
    name: "Servicepaket Basis",
    shortDescription: "Hosting, SSL, Backups, Wartung — Rabatt auf Änderungen",
    category: "Service",
    type: "servicepaket",
    priceCents: 4990,
    priceLabel: "49,90 €",
    priceNote: "Wartung inkl. · Paket-Rabatt auf Änderungen",
    processingTime: "Laufend",
    highlights: ["Updates", "Sicherheit", "SSL", "Basis-Support"],
    purchasable: true,
    billingInterval: "month",
  },
  {
    id: "servicepaket-business",
    slug: "servicepaket-business",
    name: "Servicepaket Business",
    shortDescription: "1 h/Monat inkl. · Priorität · Paket-Rabatt",
    category: "Service",
    type: "servicepaket",
    priceCents: 9990,
    priceLabel: "99,90 €",
    priceNote: "1 h/Monat inkl. · vergünstigte Weiterarbeit",
    processingTime: "Laufend",
    highlights: ["Priorisiert", "Kleinere Änderungen", "Performance-Check"],
    purchasable: true,
    billingInterval: "month",
  },
  {
    id: "servicepaket-premium",
    slug: "servicepaket-premium",
    name: "Servicepaket Premium",
    shortDescription: "3 h/Monat inkl. · Weiterentwicklung zum vergünstigten Satz",
    category: "Service",
    type: "servicepaket",
    priceCents: 19990,
    priceLabel: "199,90 €",
    priceNote: "3 h/Monat inkl. · erweiterter Paket-Rabatt",
    processingTime: "Laufend",
    highlights: ["3 h Änderungen inkl.", "Paket-Rabatt auf Weiterarbeit", "Optimierung", "Strategie"],
    purchasable: true,
    billingInterval: "month",
  },
  {
    id: "servicepaket-enterprise",
    slug: "servicepaket-enterprise",
    name: "Servicepaket Enterprise",
    shortDescription: "1 h inkl. + bis 15 h/Monat vergünstigt · höchste Priorität",
    category: "Service",
    type: "servicepaket",
    priceCents: 39990,
    priceLabel: "399,90 €",
    priceNote: "Enterprise-Kontingent · maximaler Paket-Rabatt",
    processingTime: "Laufend",
    highlights: [
      "1 h inkl. + bis 15 h/Monat",
      "Maximaler Paket-Rabatt",
      "Dedizierter Ansprechpartner",
      "Höchste Priorität",
    ],
    purchasable: true,
    billingInterval: "month",
  },
] as const;

/** Öffentlich buchbare Produkte — schlanker Checkout-Kanal */
export const PUBLIC_SHOP_SLUGS = [
  "analyse-quick",
  "analyse-business",
  "analyse-premium",
  "servicepaket-basis",
  "servicepaket-business",
  "servicepaket-premium",
  "servicepaket-enterprise",
] as const;

export type PublicShopSlug = (typeof PUBLIC_SHOP_SLUGS)[number];

export const PUBLIC_SHOP_CATEGORIES = ["Analyse", "Service"] as const;

export function isPublicShopSlug(slug: string): slug is PublicShopSlug {
  return (PUBLIC_SHOP_SLUGS as readonly string[]).includes(slug);
}

export const SHOP_CATEGORIES = [
  "Analyse",
  "Infrastruktur",
  "Templates",
  "Einrichtung",
  "Integration",
  "Marketing",
  "Beratung",
  "Service",
] as const;

export function getShopProduct(slug: string): ShopProduct | undefined {
  if (!isPublicShopSlug(slug)) return undefined;
  return SHOP_PRODUCTS.find((p) => p.slug === slug);
}

/** Studio: voller Katalog inkl. nicht-öffentlicher Leistungen */
export function getStudioCatalogProduct(slug: string): ShopProduct | undefined {
  return SHOP_PRODUCTS.find((p) => p.slug === slug);
}

export function listPurchasableProducts(): ShopProduct[] {
  return SHOP_PRODUCTS.filter((p) => isPublicShopSlug(p.slug));
}

export function listProductsByCategory(category: string): ShopProduct[] {
  return SHOP_PRODUCTS.filter((p) => p.category === category && isPublicShopSlug(p.slug));
}

export function listStudioCatalogProducts(): ShopProduct[] {
  return SHOP_PRODUCTS.filter((p) => p.studioCatalog !== false);
}
