import type { Community } from "@/types/community";

/** Simulierte Communities für Beta/Demo — inspiriert von Landingpage-Referenzen */
export const MOCK_COMMUNITIES: Community[] = [
  {
    id: "mock-rl",
    slug: "rocket-league-ssl",
    title: "Rocket League SSL Coaching",
    description:
      "Elite Coaching für Rocket League — von Diamond bis SSL. Taktik, Mechaniken, Replay-Reviews und Turniervorbereitung.",
    bannerGradient: "from-orange-500/90 via-red-600/80 to-amber-900/70",
    platformType: "discord",
    category: "Gaming",
    tags: ["Rocket League", "SSL", "Coaching", "Esports"],
    focusTags: ["Coaching", "Analyse", "Turniere", "Community"],
    communityLevel: "diamond",
    levelScore: 72,
    showMemberArea: true,
    memberCount: 1240,
    rating: 4.9,
    reviewCount: 84,
    isVerified: true,
    isTrending: true,
    visibility: "public",
    creatorName: "Edu UNZE Demo",
    creatorId: "mock-creator-1",
    externalUrl: "https://discord.com",
    createdAt: "2024-06-01T09:00:00Z",
    viewCount: 98500,
  },
  {
    id: "mock-biz",
    slug: "business-circle-dach",
    title: "Business Circle DACH",
    description:
      "Netzwerk für Unternehmer, Marketer und Gründer im DACH-Raum. Masterminds & Service-Börse.",
    bannerGradient: "from-slate-700/90 via-blue-800/80 to-indigo-900/70",
    platformType: "unze",
    category: "Business",
    tags: ["Networking", "Marketing", "DACH"],
    focusTags: ["Netzwerk", "Marketing", "Investments", "Events"],
    communityLevel: "platinum",
    levelScore: 58,
    showMemberArea: true,
    memberCount: 890,
    rating: 4.7,
    reviewCount: 42,
    isVerified: true,
    isTrending: true,
    visibility: "public",
    creatorName: "Edu UNZE Demo",
    creatorId: "mock-creator-1",
    createdAt: "2024-05-01T09:00:00Z",
    viewCount: 64200,
  },
  {
    id: "mock-lounge",
    slug: "creator-lounge",
    title: "Creator Lounge",
    description:
      "Hub für Creator: Ankündigungen, Collabs und Community-Events — kein Social-Media-Klon.",
    bannerGradient: "from-pink-500/90 via-rose-600/80 to-orange-800/70",
    platformType: "unze",
    category: "Kreativität",
    tags: ["Creator", "Collab", "Events"],
    focusTags: ["Community", "Collabs", "Events", "Netzwerk"],
    communityLevel: "gold",
    levelScore: 46,
    showMemberArea: true,
    memberCount: 2100,
    rating: 4.8,
    reviewCount: 156,
    isVerified: true,
    isTrending: true,
    visibility: "public",
    creatorName: "Edu UNZE Demo",
    creatorId: "mock-creator-1",
    createdAt: "2024-04-15T09:00:00Z",
    viewCount: 156000,
  },
  {
    id: "mock-1",
    slug: "creator-hub",
    title: "Creator Hub",
    description:
      "Netzwerk für Creator, die Communities aufbauen und monetarisieren wollen. Austausch zu Wachstum, Content-Strategie und Community-Management.",
    bannerGradient: "from-emerald-500/90 via-teal-600/80 to-cyan-700/70",
    platformType: "unze",
    category: "Kreativität",
    tags: ["Creator", "Networking", "Wachstum"],
    focusTags: ["Networking", "Community", "Events"],
    communityLevel: "gold",
    levelScore: 48,
    showMemberArea: true,
    memberCount: 2840,
    rating: 4.9,
    reviewCount: 128,
    isVerified: true,
    isTrending: true,
    visibility: "public",
    creatorName: "UNZE Team",
    creatorId: "mock-creator-1",
    createdAt: "2024-03-12T08:00:00Z",
    viewCount: 38544,
  },
  {
    id: "mock-2",
    slug: "fitness-mindset",
    title: "Fitness Mindset",
    description:
      "Motivation, Trainingspläne und Accountability für deine Fitness-Reise. Private Community mit manueller Freigabe.",
    bannerGradient: "from-green-500/85 via-emerald-600/75 to-teal-700/65",
    platformType: "whatsapp",
    category: "Fitness",
    tags: ["Training", "Ernährung", "Accountability"],
    focusTags: ["Coaching", "Community", "Events"],
    communityLevel: "platinum",
    levelScore: 62,
    showMemberArea: true,
    memberCount: 15200,
    rating: 4.7,
    reviewCount: 412,
    isVerified: true,
    visibility: "private",
    creatorName: "Sarah M.",
    creatorId: "mock-creator-2",
    createdAt: "2024-01-20T12:00:00Z",
    viewCount: 198200,
  },
  {
    id: "mock-3",
    slug: "dev-builders",
    title: "Dev Builders",
    description:
      "Entwickler-Community für Side Projects, Feedback und gemeinsames Lernen. Aufnahme aktuell pausiert — Warteliste aktiv.",
    bannerGradient: "from-slate-700/90 via-slate-800/80 to-zinc-900/75",
    platformType: "discord",
    category: "Technologie",
    tags: ["Coding", "Startups", "Open Source"],
    focusTags: ["Mentoring", "Netzwerk", "Projekte"],
    communityLevel: "silver",
    levelScore: 32,
    showMemberArea: true,
    memberCount: 8900,
    rating: 4.8,
    reviewCount: 256,
    isVerified: false,
    isTrending: true,
    visibility: "public",
    creatorName: "Alex K.",
    creatorId: "mock-creator-3",
    createdAt: "2023-11-05T16:00:00Z",
    viewCount: 112400,
  },
  {
    id: "mock-4",
    slug: "immobilien-invest",
    title: "Immobilien Investment Club",
    description:
      "Professionelles Netzwerk für Immobilien-Investoren. Marktanalysen, Deal-Bewertungen und direkter Austausch mit erfahrenen Investoren.",
    bannerGradient: "from-amber-500/85 via-orange-600/75 to-red-700/65",
    platformType: "telegram",
    category: "Finanzen",
    tags: ["Invest", "Deals", "Premium"],
    focusTags: ["Investments", "Netzwerk", "Finanzierung"],
    communityLevel: "diamond",
    levelScore: 74,
    showMemberArea: true,
    memberCount: 312,
    rating: 4.5,
    reviewCount: 2,
    isVerified: true,
    isTrending: false,
    visibility: "premium",
    monetizationEnabled: true,
    creatorName: "Thomas R.",
    creatorId: "mock-creator-4",
    priceLabel: "79,00 € einmalig",
    createdAt: "2024-05-17T10:00:00Z",
    viewCount: 38544,
  },
  {
    id: "mock-5",
    slug: "gaming-legends",
    title: "Gaming Legends DACH",
    description:
      "Offene Gaming-Community für Casual & Competitive. Sofortiger Beitritt, wöchentliche Turniere und Squad-Finder.",
    bannerGradient: "from-violet-600/80 via-purple-700/70 to-indigo-800/65",
    platformType: "discord",
    category: "Gaming",
    tags: ["Esports", "Co-op", "Turniere"],
    focusTags: ["Coaching", "Turniere", "Analyse", "Community"],
    communityLevel: "gold",
    levelScore: 45,
    showMemberArea: true,
    memberCount: 42100,
    rating: 4.6,
    reviewCount: 890,
    isVerified: true,
    isTrending: true,
    visibility: "public",
    creatorName: "UNZE Team",
    creatorId: "mock-creator-1",
    createdAt: "2024-06-01T09:00:00Z",
    viewCount: 520000,
  },
  {
    id: "mock-6",
    slug: "elite-network",
    title: "Elite Business Network",
    description:
      "Exklusives Netzwerk für Gründer und Führungskräfte. Nur auf Einladung — Bewerbungen ohne Code nicht möglich.",
    bannerGradient: "from-neutral-600/85 via-stone-700/75 to-neutral-800/70",
    platformType: "unze",
    category: "Business",
    tags: ["Exklusiv", "Founders", "Invite"],
    focusTags: ["Netzwerk", "Investments"],
    communityLevel: "elite",
    levelScore: 88,
    showMemberArea: true,
    memberCount: 98,
    rating: 5.0,
    reviewCount: 12,
    isVerified: true,
    isTrending: false,
    visibility: "private",
    creatorName: "Thomas R.",
    creatorId: "mock-creator-4",
    createdAt: "2024-02-14T08:00:00Z",
    viewCount: 4200,
  },
];
